[package]
name = "input"
version = "0.1.0"
edition = "2021"

[dependencies]
rand.version = "0.8.5"
rand.default-features = false
rand.features = ["small_rng"]

cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
rp-pico = "0.9.0"
